[project]
name = "mnist-recipe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "lark>=1.2.2",
    "mdi-python-tools",
    "pytest>=8.3.5",
    "python-dotenv>=1.1.0",
    "tensorboard>=2.19.0",
    "torch>=2.6.0",
    "torchmetrics>=1.7.0",
    "torchvision>=0.21.0",
    "tqdm>=4.67.1",
]

[tool.uv.sources]
mdi-python-tools = { path = "../mdi-cli", editable = true }  # mdi-cli is currently added as a locally cloned repo. It should be added as a package.

[tool.ruff]
extend-include = ["*.ipynb"]
line-length = 120 # This should match the 'line-length' in 'pyproject.toml'
lint.select = ["C4", "E", "F","B", "I", "W", "RUF", "Q"]
