[project]
name = "recipe-classification"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "lark>=1.2.2",
    "mdi-python-tools==0.1.4",
    "pytest>=8.3.5",
    "python-dotenv>=1.1.0",
    "torch>=2.6.0",
    "torchmetrics>=1.7.0",
    "torchvision>=0.21.0",
    "tqdm>=4.67.1",
]

# Add mdi-cli as package: "uv add --default-index https://test.pypi.org/simple/ --index https://pypi.org/simple/ mdi-python-tools==0.1.3"
# Add local mdi-cli repo as a dependency with editable install "uv add --editable ../mdi-cli"

[tool.ruff]
extend-include = ["*.ipynb"]
line-length = 120 # This should match the 'line-length' in 'pyproject.toml'
lint.select = ["C4", "E", "F","B", "I", "W", "RUF", "Q"]

[[tool.uv.index]]
url = "https://pypi.org/simple/"

[[tool.uv.index]]
url = "https://test.pypi.org/simple/"
default = true
