[project]
name = "recipe-classification"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "hafnia==0.1.15",
    "lark>=1.2.2",
    "pytest>=8.3.5",
    "python-dotenv>=1.1.0",
    "torch>=2.6.0",
    "torchmetrics>=1.7.0",
    "torchvision>=0.21.0",
    "tqdm>=4.67.1",
]

# Add 'hafnia' as package: "uv add hafnia==0.1.15"
# Add local 'hafnia' repo as a dependency with editable install "uv add --editable ../hafnia"

[tool.ruff]
extend-include = ["*.ipynb"]
line-length = 120 # This should match the 'line-length' in 'pyproject.toml'
lint.select = ["C4", "E", "F","B", "I", "W", "RUF", "Q"]
